macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

check_task:
  test_script: make test
  binaries_artifacts:
      path: build/debug/extension/duckdb-deltatable-extension/*.duckdb_extension
