macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

env:
  CIRRUS_CLONE_SUBMODULES: true
  CIRRUS_WORKING_DIR: duckdb-deltatable-extension

check_task:
  build_script: make debug
  test_script: make test
  binaries_artifacts:
      path: build/debug/extension/duckdb-deltatable-extension/*.duckdb_extension
