ci:
    skip: [cargo-check, clippy, cargo-fmt]

repos:
    - repo: https://github.com/BlankSpruce/gersemi
      rev: 0.11.1
      hooks:
      - id: gersemi

    - repo: https://github.com/cmake-lint/cmake-lint
      rev: 1.4.2
      hooks:
        - id: cmakelint

    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v18.1.2
      hooks:
      - id: clang-format
        args:
          - "--sort-includes=0"
          - "-style=file"

    - repo: local
      hooks:
      - id: cargo-fmt
        name: Rust Formatter
        description: "A tool for formatting Rust code according to style guidelines."
        language: rust
        entry: rustfmt
        types: [rust]
        args:
          - "--edition=2021"

    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
       - id: cargo-check
       - id: clippy
