[package]
name = "duckdb-deltatable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = { version = "0.8.0", features = ["datafusion"] }
tokio = { version = "1.26.0", features=['rt'] }
parquet = "36.0.0"
lazy_static = "1.4.0"
duckdb-extension-framework = "0.4.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"

[[bin]]
name = "populate"

[lib]
name = "deltatable"
crate-type = ["staticlib"]
