[package]
name = "duckdb-deltatable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = { version = "0.4.0", features=[] }
tokio = { version = "1.23.0", features=['rt'] }
parquet = "33"
lazy_static = "1.4.0"
duckdb-extension-framework = "0.4.1"

[lib]
name = "deltatable"
crate-type = ["staticlib"]
