[package]
name = "duckdb-deltatable"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["duckdb-cxx"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = { version = "0.4.0", features=[] }
libc = "0.2.135"
tokio = { version = "1.21.2", features=['rt'] }
parquet = "4"
lazy_static = "1.4.0"
duckdb-extension-framework = "0.3.0"
trace = "0.1.6"
duckdb-cxx = { path = "duckdb-cxx" }

[lib]
name = "deltatable"
crate-type = ["staticlib"]
