[package]
name = "duckdb-deltatable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = { version = "0.9.0", features = ["arrow", 'parquet'], default-features = false }
tokio = { version = "1.27.0", features=['rt'], default-features = false }
parquet = { version = "40.0.0", features=["snap", "brotli", "flate2", "lz4", "zstd", "base64"], default-features = false }
lazy_static = "1.4.0"
duckdb-extension-framework = "0.4.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"

[[bin]]
name = "populate"

[lib]
name = "deltatable"
crate-type = ["staticlib"]
