name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  GEN: ninja
  RUSTC_WRAPPER: sccache

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache
    - run: sudo apt install ninja-build build-essential
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: brew install ninja
      if: ${{ matrix.os == 'macos-14' }}

    - run: make debug

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1

    - run: make test

    - run: ls build/debug
    - uses: actions/upload-artifact@v4
      with:
        name: extension
        path: ${{github.workspace}}/build/debug/extension/duckdb-deltatable-extension/*.duckdb_extension
