name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: hendrikmuhs/ccache-action@v1.2
    - run: sudo apt install ninja-build build-essential

    - run: make debug
      env:
        GEN: ninja

    - name: Test
      working-directory: ${{github.workspace}}/build/debug/extension/test_extension
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
    - run: ls build/debug
    - uses: actions/upload-artifact@v3
      with:
        name: extension
        path: ${{github.workspace}}/build/debug/extension/test_extension/*.duckdb_extension
