name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  GEN: ninja
  RUSTC_WRAPPER: sccache
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_SIZE: 5GB
  NINJA_FLAGS: '-l 1'

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: mozilla-actions/sccache-action@v0.0.4
    - run: sudo apt install ninja-build build-essential
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: brew install ninja
      if: ${{ matrix.os == 'macos-14' }}

    - uses: rui314/setup-mold@v1
      with:
        mold-version: 1.1.1
        make-default: true

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - run: make debug
    - run: make test

    - run: ls build/debug
    - uses: actions/upload-artifact@v4
      with:
        name: extension-${{ matrix.os }}
        path: ${{github.workspace}}/build/debug/repository
        if-no-files-found: error

  upload:
    runs-on: ubuntu-latest

    needs: build

    # Deploy to the github-pages environment
    environment:
      name: netlify
      url: ${{ steps.deployment.outputs.deploy-url }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: extension-*
          path: _site
          merge-multiple: true
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './_site'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

