name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  GEN: ninja
  RUSTC_WRAPPER: sccache
  CMAKE_MAKE_PROGRAM: ninja

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.distro }}
    
    strategy:
      matrix:
        distro: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      with:
        version: 1.10.0

    - run: ninja --version
    - run: cmake --version

    - run: make debug
    - run: make test

    - run: ls build/debug
    - uses: actions/upload-artifact@v4
      with:
        name: extension
        path: ${{github.workspace}}/build/debug/extension/duckdb-deltatable-extension/*.duckdb_extension
